const ActionType ={
    USER_SIGNUP_REQ:"USER_SIGNUP_REQ",
    USER_SIGNUP_SUCCESS:"USER_SIGNUP_SUCCESS",
    USER_SIGNUP_ERROR:"USER_SIGNUP_ERROR",
    USER_SIGNUP_EMPTY:"USER_SIGNUP_EMPTY",

    //LOGIN 
    USER_LOGIN_REQ:"USER_LOGIN_REQ",
    USER_LOGIN_SUCCESS:"USER_LOGIN_SUCCESS",
    USER_LOGIN_ERROR:"USER_LOGIN_ERROR",
    USER_LOGIN_EMPTY:"USER_LOGIN_EMPTY",
}

module.exports = ActionType